package com.brettyin.cardshelper.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.brettyin.cardshelper.model.GameToPlayer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table GAME_TO_PLAYER.
*/
public class GameToPlayerDao extends AbstractDao<GameToPlayer, Void> {

    public static final String TABLENAME = "GAME_TO_PLAYER";

    /**
     * Properties of entity GameToPlayer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property GameId = new Property(0, long.class, "gameId", false, "GAME_ID");
        public final static Property PlayerId = new Property(1, Long.class, "playerId", false, "PLAYER_ID");
        public final static Property Status = new Property(2, Integer.class, "Status", false, "STATUS");
        public final static Property Level = new Property(3, Integer.class, "Level", false, "LEVEL");
    };

    private DaoSession daoSession;

    private Query<GameToPlayer> game_GameToPlayerListQuery;

    public GameToPlayerDao(DaoConfig config) {
        super(config);
    }
    
    public GameToPlayerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'GAME_TO_PLAYER' (" + //
                "'GAME_ID' INTEGER NOT NULL ," + // 0: gameId
                "'PLAYER_ID' INTEGER," + // 1: playerId
                "'STATUS' INTEGER," + // 2: Status
                "'LEVEL' INTEGER);"); // 3: Level
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'GAME_TO_PLAYER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GameToPlayer entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGameId());
 
        Long playerId = entity.getPlayerId();
        if (playerId != null) {
            stmt.bindLong(2, playerId);
        }
 
        Integer Status = entity.getStatus();
        if (Status != null) {
            stmt.bindLong(3, Status);
        }
 
        Integer Level = entity.getLevel();
        if (Level != null) {
            stmt.bindLong(4, Level);
        }
    }

    @Override
    protected void attachEntity(GameToPlayer entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public GameToPlayer readEntity(Cursor cursor, int offset) {
        GameToPlayer entity = new GameToPlayer( //
            cursor.getLong(offset + 0), // gameId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // playerId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // Status
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3) // Level
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GameToPlayer entity, int offset) {
        entity.setGameId(cursor.getLong(offset + 0));
        entity.setPlayerId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setStatus(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setLevel(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(GameToPlayer entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(GameToPlayer entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "gameToPlayerList" to-many relationship of Game. */
    public List<GameToPlayer> _queryGame_GameToPlayerList(long gameId) {
        synchronized (this) {
            if (game_GameToPlayerListQuery == null) {
                QueryBuilder<GameToPlayer> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GameId.eq(null));
                game_GameToPlayerListQuery = queryBuilder.build();
            }
        }
        Query<GameToPlayer> query = game_GameToPlayerListQuery.forCurrentThread();
        query.setParameter(0, gameId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPlayerDao().getAllColumns());
            builder.append(" FROM GAME_TO_PLAYER T");
            builder.append(" LEFT JOIN PLAYER T0 ON T.'PLAYER_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected GameToPlayer loadCurrentDeep(Cursor cursor, boolean lock) {
        GameToPlayer entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Player player = loadCurrentOther(daoSession.getPlayerDao(), cursor, offset);
        entity.setPlayer(player);

        return entity;    
    }

    public GameToPlayer loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<GameToPlayer> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<GameToPlayer> list = new ArrayList<GameToPlayer>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<GameToPlayer> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<GameToPlayer> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
